// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package dto

type CreateUserResult interface {
	IsCreateUserResult()
}

type GraphError interface {
	IsGraphError()
	GetMessage() string
	GetCode() string
}

type UserResult interface {
	IsUserResult()
}

type UserSessionResult interface {
	IsUserSessionResult()
}

type CreateUserPayload struct {
	GivenName  *string `json:"givenName,omitempty"`
	FamilyName *string `json:"familyName,omitempty"`
	Email      string  `json:"email"`
	Password   string  `json:"password"`
}

type EmailUnavailable struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func (EmailUnavailable) IsGraphError()           {}
func (this EmailUnavailable) GetMessage() string { return this.Message }
func (this EmailUnavailable) GetCode() string    { return this.Code }

func (EmailUnavailable) IsCreateUserResult() {}

type InvalidCredentials struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func (InvalidCredentials) IsGraphError()           {}
func (this InvalidCredentials) GetMessage() string { return this.Message }
func (this InvalidCredentials) GetCode() string    { return this.Code }

func (InvalidCredentials) IsUserSessionResult() {}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID         string  `json:"id"`
	GivenName  *string `json:"givenName,omitempty"`
	FamilyName *string `json:"familyName,omitempty"`
	Email      string  `json:"email"`
	AvatarURL  *string `json:"avatarUrl,omitempty"`
}

func (User) IsUserResult() {}

func (User) IsCreateUserResult() {}

type UserNotFound struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func (UserNotFound) IsGraphError()           {}
func (this UserNotFound) GetMessage() string { return this.Message }
func (this UserNotFound) GetCode() string    { return this.Code }

func (UserNotFound) IsUserResult() {}

func (UserNotFound) IsUserSessionResult() {}

type UserSession struct {
	Token     string `json:"token"`
	ExpiresAt string `json:"expiresAt"`
}

func (UserSession) IsUserSessionResult() {}
