// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	GivenName     *string            `json:"given_name"`
	FamilyName    *string            `json:"family_name"`
	Email         string             `json:"email"`
	EmailVerified *bool              `json:"email_verified"`
	AvatarUrl     *string            `json:"avatar_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}

type UserAuth struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Value        string             `json:"value"`
	Provider     string             `json:"provider"`
	ProviderID   string             `json:"provider_id"`
	ProviderData []byte             `json:"provider_data"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Version      int32              `json:"version"`
}

type UserSession struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	ImpersonatorID pgtype.UUID        `json:"impersonator_id"`
	Token          string             `json:"token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	UserExpired    bool               `json:"user_expired"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Version        int32              `json:"version"`
}
